// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PenosasStrikeGPS
{
        public const string achievement_got_50_points = "CgkI3NSysNEXEAIQAg"; // <GPGSID>
        public const string achievement_got_500_points = "CgkI3NSysNEXEAIQBg"; // <GPGSID>
        public const string achievement_flawless_insane_mode = "CgkI3NSysNEXEAIQCA"; // <GPGSID>
        public const string achievement_broke_a_record = "CgkI3NSysNEXEAIQDA"; // <GPGSID>
        public const string achievement_got_300_points = "CgkI3NSysNEXEAIQBQ"; // <GPGSID>
        public const string leaderboard_easy = "CgkI3NSysNEXEAIQCg"; // <GPGSID>
        public const string achievement_insane_mode_activated = "CgkI3NSysNEXEAIQBA"; // <GPGSID>
        public const string leaderboard_medium = "CgkI3NSysNEXEAIQAQ"; // <GPGSID>
        public const string achievement_got_25_points = "CgkI3NSysNEXEAIQDg"; // <GPGSID>
        public const string leaderboard_hard = "CgkI3NSysNEXEAIQCw"; // <GPGSID>
        public const string achievement_got_999_points = "CgkI3NSysNEXEAIQBw"; // <GPGSID>
        public const string achievement_got_100_points = "CgkI3NSysNEXEAIQAw"; // <GPGSID>
        public const string achievement_insane_mode_activated_hard = "CgkI3NSysNEXEAIQCQ"; // <GPGSID>
        public const string achievement_earned_a_life = "CgkI3NSysNEXEAIQDQ"; // <GPGSID>

}

